# Generated by Django 2.2.7 on 2019-11-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20191118_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['published_date']},
        ),
    ]
